apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-operator
spec:
  template:
    spec:
      containers:
        - name: jaeger-operator
          env:
            - name: WATCH_NAMESPACE
              value: ""
              valueFrom: null
