apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./config/install

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: grafana-operator-controller-manager
    path: patches/grafana-image-version.yaml
