apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  allInOne:
    options:
      log-level: info
  storage:
    type: memory
    options:
      memory:
        max-traces: 100000
