apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    name: jaeger-operator
  name: jaeger-operator-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
