apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: observability/jaeger-operator-serving-cert
  labels:
    name: jaeger-operator
  name: jaeger-operator-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: jaeger-operator-webhook-service
        namespace: observability
        path: /mutate-v1-deployment
    failurePolicy: Ignore
    name: deployment.sidecar-injector.jaegertracing.io
    objectSelector:
      matchExpressions:
        - key: name
          operator: NotIn
          values:
            - jaeger-operator
    rules:
      - apiGroups:
          - apps
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - deployments
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: jaeger-operator-webhook-service
        namespace: observability
        path: /mutate-jaegertracing-io-v1-jaeger
    failurePolicy: Fail
    name: mjaeger.kb.io
    rules:
      - apiGroups:
          - jaegertracing.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - jaegers
    sideEffects: None
